### ISSUE TITLE
Time Complexity / Runtime Speed for "generic" algorithm using Precomputed Sparse Distance Matrix

### ISSUE THREAD

**Issue by windweller** [scikit-learn-contrib/hdbscan#126]
I'm using a custom distance function (edit distance) so I computed sparse distance matrix (thank @lmcinnes for the advice). My other choice is to use cosine distance on feature vectors but it seems like cosine distance is not usable at this moment...

May I ask if there is a slowdown for using the precomputed sparse distance matrix? (Is it as slow as the single linkage from fastcluster/scipy?)

Is there still a way to use cosine distance on feature vectors? (It was mentioned in another issue that there's a "bug", but I was wondering if somehow I can still use it).

**Comment by lmcinnes** [comment]
There is definitely a cost to precomputed sparse distance matrices (and indeed, precomputed distance matrices of any kind). It is approximately the same speed as the single linkage from fastcluster, and hence better than single linkage from scipy (I need to submit a pull request to improve that at some point).

Strict cosine distance for feature vectors isn't really a thing since cosine distance does not obey the triangle inequality, which is required for fast performance on feature vectors. You can use angular distance instead (by l2- normalising all the vectors and using euclidean distance) but that is not strictly the same thing. Jaccard may also be an option if you are working with sparse feature vectors. Beware of high dimensionality however, as that will greatly tax the feature vector implementation.

A final option is to look at dimension reduction (think LSI style) prior to clustering. You can do matrix factorization and/or non-linear dimension reduction to get to a small number of dimensions.
