### ISSUE TITLE
Identifying the influence of a feature on a sample's cluster assignment

### ISSUE THREAD

**Issue by dremekie** [scikit-learn-contrib/hdbscan#132]
Taken a set of features: `[a, b, c]` for a set of samples: X, Y, Z.

If X is "assigned" to cluster 1, can I answer the following question:

How much did feature `a` contribute to sample X's assignment to cluster 1?

**Comment by lmcinnes** [comment]
Not straight-fowardly unfortunately. It may be possible to derive such a
thing, but since the clustering is density based and relies on distance it
would not be trivial. I will certainly think about it, since I agree it is
certainly an interesting question, but I can't provide any immediate
answers, or even any promise that I will be able to come up with a valid
way to answer the question.
