### ISSUE TITLE
Example BUG: Bug in the example in the Readme

### ISSUE THREAD

**Issue by Toblerone11** [scikit-learn-contrib/hdbscan#138]
In line 7 of the example presented in the Readme, there is a bug:
running the line `alt_labels = hierarchy.get_clusters(0.100, 5)` resulted with the following exception:

```
Traceback (most recent call last):
...
    alt_labels = hierarchy.get_clusters(0.100, 5)
  File "/home/dev/.local/lib/python2.7/site-packages/hdbscan/plots.py", line 686, in get_clusters
    return labelling_at_cut(self._linkage, cut_distance, min_cluster_size)
TypeError: Argument 'linkage' has incorrect type (expected numpy.ndarray, got SingleLinkageTree)
```

It can be solved by changing line 6 to `hierarchy = clusterer.cluster_hierarchy_._linkage`

running python 2.7

**Comment by lmcinnes** [comment]
Thanks for catching this. I admit that I am a little puzzled:I feel like the code as is should work. I'll have to look into that --  Let me get back to you.

**Comment by ahirner** [comment]
All tree building functions already wrap results in a `SingleLinkageTree` object. This can be fixed by dereferencing to the underlying ndarray in master (`robust_single_linkage.py`, line 297):
```python
return labels, single_linkage_tree.to_numpy() #or ._linkage, depending on intended mutations downstream
```
Also, on my setup (3.6.3 and sklearn 0.19.1) the generated data includes labels which also must be dereferenced in the readme. 
Should I make a PR?

**Comment by lmcinnes** [comment]
I don't have a lot of time at the moment so a PR would be greatly appreciated.
