### ISSUE TITLE
Principled Way to reduce size of noise class: URGENT

### ISSUE THREAD

**Issue by pGit1** [scikit-learn-contrib/hdbscan#154]
Hi! I am playing around with HDBSCAN on a dataset to see if it will work for our needs and no matter how I change the hyperparameters I keep getting a giant noise class. Ive set the cluster_selection_method to "leaf", Ive set min_samples=1 and even lowered the value of alpha **all** to no avail. Ideally I would want to see if the algorithm can create relatively small noise clusters but I cannot find the parameters to do so. 

Any help would be much appreciated.

**Comment by lmcinnes** [comment]
Fundamentally as a density based algorithm HDBSCAN is going to constrast high density with the remainder. If you have a lot of even density data and pockets of high density then all that low density data is "noise" by any reasonable measure. It is essentially baked into the assumptions of the algorithm about what a cluster means. If you desperately need to assign other points to clusters you could look at the ``membership_vector`` or ``all_points_membership`` in the prediction module which will try to assign some level of cluster membership to all points. Fundamentally it sounds like you actually want to partition your data. You may be more happy with Dirichlet Process Gaussian Mixture Models (assuming, of course, that your data has Gaussian clusters).

**Comment by pGit1** [comment]
Makes sense thank you!

**Comment by rtmatx** [comment]
@lmcinnes Shouldn't the `leaf` option capture lot of even density data points as a cluster(s). 

I am confused with what `leaf` option is doing that is different from `eom` method. On what basis are clusters produced in `leaf` method. Since the clusters produced can have different density, I am guessing that a flat cut is not made at a particular `lambda` level. I have experimented with `eom` and `leaf` method on several datasets. I have noticed that even though `leaf` option creates lot of clusters for similar parameters as `eom`, it also generates lot amount of anomalies than before

Can you point to any documentation that has reference to `leaf` method or is going through the `cython` code in this package the best way to understand this

**Comment by lmcinnes** [comment]
The ``leaf`` option will literally just select the leaves of the condensed tree. By definition this will result in a lot more noise points. Thus the ``leaf`` option will find the densest regions, but isn't a flat cut since the densities of different dense regions may vary.

**Comment by rtmatx** [comment]
Thanks. I feel so stupid now in asking this. Sorry for taking your time on this
