### ISSUE TITLE
Playing with dimension numbers

### ISSUE THREAD

**Issue by snakers4** [scikit-learn-contrib/hdbscan#167]
@lmcinnes 
This is more of a practical observation.

All the examples [http://hdbscan.readthedocs.io/en/latest/performance_and_scalability.html](here) are based on 10-dimension vectors.

In practice I wanted to apply HDBSCAN to clustering images using CNN activations and skip connections (5000+ dimension vector). So I tried PCA and observed the following:

- 500k samples * 10 - 50 dimensions seem to work fine;
- Anything above 100 dimensions just stalls w/o significant memory and CPU consumption;

Did not see the mentioning of dimensionality in the docs explicitly, so may be this will be of help to anybody.

**Comment by lmcinnes** [comment]
Yes, you are correct, as you scale up dimension things can go badly. I should add something to the FAQ about that. Of course a lot is dataset dependent; sometimes 5000 dimensional data can work fine if the data distribution happens to be amenable. Still, this is a serious issue, and is actually one of the things I am currently working on. The first line of attack is to improve dimension reduction techniques; right now that takes the form of [UMAP](http://github.com/lmcinnes/umap) which can perform t-SNE like manifold learning dimension reduction (to arbitrary embedding dimension rather than just 2 or 3). It is till in development, and I would suggest if you wish to try it on your data you use the ``new_layout`` branch (which will soon be merged into master). The second approach is to use approximate k-nearest neighbor approaches that scale better with dimension to build a fast approximate HDBSCAN. I don't yet have code for that, although I believe the ideas are all in place at this point.

**Comment by snakers4** [comment]
Many thanks for your comment!

So it is reasonable to try UMAP instead of PCA for dimensionality reduction as a pre-processing step, right?

**Comment by lmcinnes** [comment]
With the usual caveats about it being experimental, and that one needs to be careful and verify your clustering results make sense ... yes that should be feasible. I believe there is an issue in UMAP on clustering after using UMAP where I discuss some of the things to be wary of and why.

**Comment by snakers4** [comment]
Many thanks.
PCA + naive filtering worked fine in my case, better than HDBSCAN.
Probably because data was quite homogeneous and linearly separable.

**Comment by zabzug-pfpt** [comment]
@lmcinnes I'm encountering this same quirk ~2 years later! My impression of most clustering algorithms I've played with is that they're generally approximately _O(dn^2)_ as long as your dimensionality is "reasonable". Do you have any idea why HDBSCAN runtime is so sensitive to the dimensionality of the data? Some concrete numbers with n = 16000 and d = 64:
- HDBSCAN runtime: 15.9 seconds
- sklearn DBSCAN runtime: 1.3 seconds

Also, with n = 32000:
- HDBSCAN runtime @ d = 16: 5.2 seconds
- HDBSCAN runtime @ d = 64: 56.2 seconds

**Comment by lmcinnes** [comment]
There is a cutoff when the code opts for a different code path that is slower but scales much better with dimension. I believe that the current value is 64; I haven't evaluated this in some time, and it might be worth adjusting. Thanks.
