### ISSUE TITLE
Is normalization beneficial for hdbscan?

### ISSUE THREAD

**Issue by joshjacobson** [scikit-learn-contrib/hdbscan#182]
This algorithm has the appearance of being robust to features of vastly different scale without normalization; is this reading of it correct?

**Comment by lmcinnes** [comment]
Yes and no. Because it supports arbitrary shapes of clusters this includes long spindly looking clusters that can result from features on wildly different scales, so in that sense, yes it does. On the other hand the scaling between your features has to be meaningful in the sense of distance -- if I measure weight in kg and height in mm and cluster people using a Euclidean distance over those features it is going to have a preference for grouping by weights which will appear "closer" rather than heights. So, as long as the difference in feature scales are *meaningful* (and that is purely application driven) then yes, it will work, but one still needs to be careful as to the meaning of those different feature scales.
