### ISSUE TITLE
Extracting Nearest Neighbors from HDBSCAN

### ISSUE THREAD

**Issue by ixxie** [scikit-learn-contrib/hdbscan#208]
Our pipeline leverages HDBSCAN to cluster points in a vector space. We are also interested in getting the K nearest neighbors, and knowing that HDBSCAN already uses ball trees to cluster I was wondering if they can also be made available to infer the nearest neighbors, saving us duplicated computation.

The documentation mentions the minimal spanning tree and the single linkage tree are available, but it is not entirely clear to me if these contain the information needed to infer the nearest neighbors. Is there a way to obtain it? I am open to hacking on HDBSCAN and submitting a PR if you could give some pointers on where to begin!

**Comment by lmcinnes** [comment]
That information doesn't get cached unfortunately. This HDBSCAN implementation is already somewhat memory hungry because of the various structures it keeps, and all that is really needed is the distance to the kth nearest neighbor, not the full neighbor list, so it gets discarded pretty quickly. As an alternative (if computation time is the issue) I have a small approximate nearest neighbor library [pynndescent](https://github.com/lmcinnes/pynndescent) which can find k-nearest neighbors very quickly even for high dimensional data -- in fact the next generation hdbscan will be built off this instead of kd-trees or ball-trees. It does only find the approximate nearest neighbors (i.e. sometimes it gets you the 11th and 12th neighbors and misses the 9th and 10th, say, when asking for 10 neighbors) but the tradeoff in terms of speed is significant as soon as you are outside standard cases for space tree algorithms (high ambient dimension being the most likely).

**Comment by ixxie** [comment]
Well it makes sense with the complexity of HDBSCAN that memory will be an issue. Thanks for the tip on pynndescent, will try that out when the time comes for a nearest-neighbor algorithm.

**Comment by ixxie** [comment]
Well it makes sense with the complexity of HDBSCAN that memory will be an issue. Thanks for the tip on pynndescent, will try that out when the time comes for a nearest-neighbor algorithm.
