### ISSUE TITLE
Expected Runtimes, Dimensionality Reduction

### ISSUE THREAD

**Issue by gabrieldernbach** [scikit-learn-contrib/hdbscan#456]
I was running hdbscan on 500K datapoints of 128 dimensions each.

From the lovely documentation `https://hdbscan.readthedocs.io/en/latest/performance_and_scalability.html#but-should-i-get-a-coffee` I was expecting this to run "over lunch".
The fit took roughly twelve hours, a magnificent lunch break.
I believe this difference is due to the higher dimensions (128 >> 10)? Can you confirm this?

If this is the case, can you share your experience with running dimensionality reduction (pca, tsne, umap) prior to clustering with hdbscan?

My compute environment had 60G of RAM and 8 Cores (most of it ran on one core only).

**Comment by lmcinnes** [comment]
Dimensionality is the problem here. The table was for 10 dimensional data. Much of anything in the range of 2-50 should give something in the ballpark of those time-frames. Unfortunately beyond 50 dimensions the current approach has to fall back to a more generic algorithm that does not scale as well.

Your best option is to use PCA down to 40-50 dimensions, or UMAP down to 2-10 dimensions prior to running the clustering.

**Comment by gabrieldernbach** [comment]
Thanks for the quick reply, I will give it try
