### ISSUE TITLE
numpy.core._exceptions.MemoryError

### ISSUE THREAD

**Issue by ginward** [scikit-learn-contrib/hdbscan#498]
Not sure if this is related to https://github.com/scikit-learn-contrib/hdbscan/issues/345

I have 10 million data points of 5 dimensions. I am using a machine with 1.5TB RAM. I am also using the default HDBSCAN values: 

`hdbscan_model = HDBSCAN(min_cluster_size=10, metric='euclidean', cluster_selection_method='eom', prediction_data=True, core_dist_n_jobs=5)
`

My code is also based on this pull request: https://github.com/scikit-learn-contrib/hdbscan/pull/495

However, I am encountering the following memory error: 

```
Tue Oct  5 18:53:14 2021 Finished embedding
Traceback (most recent call last):
  File "BERTopic.py", line 62, in <module>
    topic_model = topic_model.fit(docs, embeddings)
  File "/scratch/ap248/nlp_env38/lib/python3.8/site-packages/bertopic/_bertopic.py", line 212, in fit
    self.fit_transform(documents, embeddings, y)
  File "/scratch/ap248/nlp_env38/lib/python3.8/site-packages/bertopic/_bertopic.py", line 291, in fit_transform
    documents, probabilities = self._cluster_embeddings(umap_embeddings, documents)
  File "/scratch/ap248/nlp_env38/lib/python3.8/site-packages/bertopic/_bertopic.py", line 1391, in _cluster_embeddings
    probabilities = hdbscan.all_points_membership_vectors(self.hdbscan_model)
  File "/scratch/ap248/nlp_env38/lib/python3.8/site-packages/hdbscan/prediction.py", line 636, in all_points_membership_vectors
    distance_vecs = all_points_dist_membership_vector(
  File "hdbscan/_prediction_utils.pyx", line 98, in hdbscan._prediction_utils.all_points_dist_membership_vector
  File "hdbscan/_prediction_utils.pyx", line 107, in hdbscan._prediction_utils.all_points_dist_membership_vector
numpy.core._exceptions.MemoryError: Unable to allocate 3.77 TiB for an array with shape (11582429, 44718) and data type float64
```

I was wondering would increasing `min_cluster_size` and reducing `min_samples` help? Why is there 44718 columns to predict? Is there 44718 clusters?

**Comment by jc-healy** [comment]
I don't think it will make a difference.  You are asking for the cluster
membership of a set of points that we trained our clustering on.  It's
probably worth verifying but I'm reasonably confident that it should work.

Regarding run speed do you mean that your clustering (the hdbscan
component) is taking 48 hours?  Or do you mean your BERtopic thing is
taking 48 hours?  I'd be very surprised if the hdbscan component was taking
two days.  I recall that when we did our benchmarks we could cluster a
million points in about 10 dimensional space over lunch.  If BERtopic is
similar to top2vec there are likely three major components to the algorithm
(though the details may vary):
1) Embedding your text into a vector space via USE, Doc2Vec or some other
technique.
2) Applying UMAP to reduce it's dimension in order to make density sensible
and improve the efficiency of clustering
3) Applying hdbscan as an efficient, noise robust clustering technique.
That finds your dense regions of documents and filters out your noise
documents.

In general the first two steps of that style of an algorithm are far more
costly than the hdbscan step.

There are also GPU accelerated variations on many of these components (UMAP
& hdbscan)that you could look at that exist over RAPIDS.
UMAP:
https://medium.com/the-artificial-impostor/umap-on-rapids-15x-speedup-f4eabfbdd978
hdbscan:
https://developer.nvidia.com/blog/gpu-accelerated-hierarchical-dbscan-with-rapids-cuml-lets-get-back-to-the-future/

Good luck.

**Comment by ginward** [comment]
@jc-healy I think it is the HDBSCAN component that is taking a very long time. You can try the following code, where I reproduce the issue with a large random dataset. Obviously the real data that I have is not random - but this just illustrates the issue. I am using a machine with 1TB of RAM at the moment. 
```

import pandas as pd

import numpy as np

from hdbscan import HDBSCAN

embeddings_ = np.random.rand(11582429,5)

# Setting HDBSCAN model
hdbscan_model = HDBSCAN(min_cluster_size=1000, min_samples=1, metric='euclidean', cluster_selection_method='eom', prediction_data=True, core_dist_n_jobs=5)

test=hdbscan_model.fit_predict(embeddings_)
```

**Comment by ginward** [comment]
@jc-healy Thanks! Would it be faster if I do not do soft-clustering? 

I noticed that in BertTopic there is a parameter called `calculate_probabilities`, which essentially calls the membership_vector function: https://github.com/MaartenGr/BERTopic/blob/0b321678ffe4eab0a28484faf76728f584a94ebd/bertopic/_bertopic.py#L1391

Would soft-clustering slow things down a lot? If that is the case, I would simply set `calculate_probabilities=False`.
