### ISSUE TITLE
Does HDBSCAN support out-of-core (incremental) training?

### ISSUE THREAD

**Issue by NightMachinary** [scikit-learn-contrib/hdbscan#521]
Does HDBSCAN support out-of-core (incremental) training? If not, that means it can only be used for data that fits on RAM, correct?

**Comment by jc-healy** [comment]
I believe that you are correct that we currently only support in-RAM
training (unless I missed a PR).  Most folks switch to large memory SMP
boxes to cluster large amounts of data.  At that point the bottleneck
starts to become run time instead of memory.  The solution to the run time
scaling tends to be pivoting to GPU implementations such as RAPIDS cuMLs
excellent implementation of our hdbscan library.  (
https://developer.nvidia.com/blog/gpu-accelerated-hierarchical-dbscan-with-rapids-cuml-lets-get-back-to-the-future/
).

**Comment by NightMachinary** [comment]
- Is this only a limitation of the implementation? Can the HDBSCAN algorithm support out-of-core training on paper?
- cuML does not seem to support out-of-core training either, and GPU memories are even more limited than RAM. It does support multi-GPU training though; will the constraint then be the sum of all available GPU memory? (My intuition here says that this would mean that supporting out-of-core training should be possible, too.)

PS: What is a large (how large? :D) memory SMP? The only relevant acronym I found was https://en.wikipedia.org/wiki/Symmetric_multiprocessing .

**Comment by jc-healy** [comment]
We've had conversations around how one might go about implementing a
distributed memory hdbscan.  I think it's probably doable with enough work
but definitely not trivial.  If one was going to go down that path I'd
suggest looking at DASK as a framework.

I agree that cuML doesn't support out-of-core implementations either.  I
guess my question becomes why one is interested in out-of-core
implementations.  If it is to allow scaling to large amounts of data then
I'm not sure it will help.  If, on the other hand, it is because you want
to be able to update your density based clustering model to account for
non-stationary data then that is a different (and really interesting)
question.

When not running on our laptops we often run hdbscan on boxes with
somewhere between 64GB of RAM and 2TB worth of RAM.  As such we're rarely
bound by not being able to fit our data into memory.  We're instead bound
by compute time.  Our current code has a million data points taking about
an hour to run and a 5 million data point set running overnight.  Those
aren't really memory bound problems, they are run time bound.  You can run
much bigger datasets than that on a large memory computer but it's going to
start taking prohibitively long to finish the computation.  As such for
larger data sets I tend to suggest pivoting to GPU models because they
reduce the computational time significantly.  That said, I haven't spent
much time stress testing the RAPIDS code base so can't tell you how large a
dataset they can run on say a video card with 32 GB of internal RAM.  That
would be a great question to ask their RAPIDS team.  I do know that they
are getting excellent performance in the 10s of millions of records range.

P.S. Sorry, I shouldn't have used an acronym that didn't bring anything
useful to the conversation.  By SMP I did indeed mean symmetric
multiprocessing.  I just use it here to mean a big computer with a single
block of shared memory accessible to all the cores as opposed to a
distributed memory system. Distributed memory systems allow you to bring
many more cores to bear on a problem but, depending on the algorithm, can
be quite difficult to program efficiently.

**Comment by NightMachinary** [comment]
How many dimensions do these records have?

My own problem is that I have around 25GB of RAM, and the data will be on the order of 100GB, so I am looking for out-of-core options. I think I'll try dimension reduction to reduce the data to a manageable size and then use cuML's HDBSCAN. 
---
Thanks for the info. Feel free to close the issue.
