### ISSUE TITLE
HDBSCAN v0.8.36 release in conda-forge

### ISSUE THREAD

**Issue by divyegala** [scikit-learn-contrib/hdbscan#638]
I see that v0.8.36 was released today and is available via pypi. Is there a timeline when it will be available in conda-forge as well?

**Comment by lmcinnes** [comment]
Soon; conda-forge monitors pypi, so a rebuild of the feedstock should get
triggered.

Leland.

**Comment by divyegala** [comment]
@lmcinnes thank you for your response. Can HBDSCAN still not work with Cython 3?

**Comment by lmcinnes** [comment]
Not currently no, and is unlikely to do so in the future. Eventually the dual tree boruvka should be ported into scikit-learn, and I have a more modern (but at the moment a little more limited) approach to HDBSCAN in [fast_hdbscan](https://github.com/TutteInstitute/fast_hdbscan) which relies on numba instead of Cython.

**Comment by vyasr** [comment]
This issue can be closed, 0.8.36 (and 0.8.37) have since been released on conda-forge.
